name: Build and Deploy Web to GitHub Pages

on:
  push:
    branches:
      - main  # ou 'master', se for o seu branch principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 游닌 Checkout do c칩digo
        uses: actions/checkout@v3

      - name: 游릭 Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 游닍 Instalar depend칡ncias
        run: npm ci

      - name: 游댏 Criar .env com vari치veis de ambiente
        run: |
          echo "EXPO_PUBLIC_APPKEY=${{ secrets.EXPO_PUBLIC_APPKEY }}" >> .env
          echo "EXPO_PUBLIC_AUTHDOMAIN=${{ secrets.EXPO_PUBLIC_AUTHDOMAIN }}" >> .env
          echo "EXPO_PUBLIC_PROJECTID=${{ secrets.EXPO_PUBLIC_PROJECTID }}" >> .env
          echo "EXPO_PUBLIC_STORAGEBUCKET=${{ secrets.EXPO_PUBLIC_STORAGEBUCKET }}" >> .env
          echo "EXPO_PUBLIC_MESSAGINGSENDERID=${{ secrets.EXPO_PUBLIC_MESSAGINGSENDERID }}" >> .env
          echo "EXPO_PUBLIC_APPID=${{ secrets.EXPO_PUBLIC_APPID }}" >> .env
          echo "EXPO_PUBLIC_WEBCLIENTID=${{ secrets.EXPO_PUBLIC_WEBCLIENTID }}" >> .env
          echo "EXPO_PUBLIC_ANDROIDCLIENT_ID=${{ secrets.EXPO_PUBLIC_ANDROIDCLIENT_ID }}" >> .env


      - name: 丘뙖잺 Build para Web
        run: npx expo export --platform web

      - name: 游 Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
